// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dthiqsermsanarcemhzv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0aGlxc2VybXNhbmFyY2VtaHp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDEwMTMsImV4cCI6MjA2NTkxNzAxM30.7wlMrGGgtI5ZJ6qVMEr0f3X3TgaQKH1QUODmVMPZbVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);